add hw15
bater091/AlevelKyryloLevchenko pull request #11
Opened 2021-12-11 18:33 UTC by bater091

2021-12-11 18:33 UTC, bater091 commented
add hw15

2021-12-13 00:19 UTC, Fabolo12 requested changes

2021-12-13 00:19 UTC, Fabolo12 commented on src/main/java/com/levchenko/hw15/BoxVolumeComparator.java
> +}
Sorts not by task condition

2021-12-13 00:19 UTC, Fabolo12 commented on src/main/java/com/levchenko/hw15/MyList.java
> +    }
Doesn't work if the list is empty

2021-12-14 00:20 UTC, Fabolo12 approved these changes
10

2021-12-14 18:18 UTC, merged